import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "@/app/globals.css"
import "@/styles/style.css";
import { ThemeProvider } from "@/components/Themes/theme-provider";
import { DockDemo } from "@/components/Custom/Dock";
import { AlertDialog } from "@radix-ui/react-alert-dialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "UI Engineer",
   description: "Generated by Phong",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" id="root">
         <body className={inter.className}>
            <ThemeProvider
               attribute="class"
               defaultTheme="light"
               enableSystem
               disableTransitionOnChange
            >
               {/* <DockDemo /> */}
               {children}
               <Toaster />
            </ThemeProvider>
         </body>
      </html>
   );
}
